/**
 * Typed DTOs for the NestJS backend.
 *
 * Generated from `docs/swagger-v2.json` into `api.gen.ts`, re-exported here under
 * flat names so services stay readable. Regenerate with `npm run api:types`;
 * never hand-edit `api.gen.ts`.
 *
 * Swagger documents the *unwrapped* payload. The wire format is still
 * `{ data, errors, statusCode }`, and `lib/axios.ts` unwraps it — so these types
 * describe exactly what a service call resolves to.
 */
import type { components } from "@/types/api.gen";

export type HealthDto = components["schemas"]["HealthDto"];
export type RegisterDto = components["schemas"]["RegisterDto"];
export type AuthUserDto = components["schemas"]["AuthUserDto"];
export type TokensDto = components["schemas"]["TokensDto"];
export type LoginDto = components["schemas"]["LoginDto"];
export type RefreshDto = components["schemas"]["RefreshDto"];
export type MessageDto = components["schemas"]["MessageDto"];
export type ForgotPasswordDto = components["schemas"]["ForgotPasswordDto"];
export type ResendCodeDto = components["schemas"]["ResendCodeDto"];
export type VerifyCodeDto = components["schemas"]["VerifyCodeDto"];
export type ResetTokenDto = components["schemas"]["ResetTokenDto"];
export type ResetPasswordDto = components["schemas"]["ResetPasswordDto"];
export type ChangePasswordDto = components["schemas"]["ChangePasswordDto"];
export type CheckUsernameDto = components["schemas"]["CheckUsernameDto"];
export type UsernameAvailableDto = components["schemas"]["UsernameAvailableDto"];
export type UploadedMediaDto = components["schemas"]["UploadedMediaDto"];
export type DeletedKeyDto = components["schemas"]["DeletedKeyDto"];
export type UserBriefDto = components["schemas"]["UserBriefDto"];
export type SuggestionDto = components["schemas"]["SuggestionDto"];
export type AddSearchTextDto = components["schemas"]["AddSearchTextDto"];
export type SearchHistoryItemDto = components["schemas"]["SearchHistoryItemDto"];
export type DeletedCountDto = components["schemas"]["DeletedCountDto"];
export type AddSearchedUserDto = components["schemas"]["AddSearchedUserDto"];
export type SearchedUserItemDto = components["schemas"]["SearchedUserItemDto"];
export type AccountDeletedDto = components["schemas"]["AccountDeletedDto"];
export type ReportUserDto = components["schemas"]["ReportUserDto"];
export type ReportCreatedDto = components["schemas"]["ReportCreatedDto"];
export type ProfileDto = components["schemas"]["ProfileDto"];
export type PostBriefDto = components["schemas"]["PostBriefDto"];
export type MusicBriefDto = components["schemas"]["MusicBriefDto"];
export type ActivityItemDto = components["schemas"]["ActivityItemDto"];
export type UpdateProfileDto = components["schemas"]["UpdateProfileDto"];
export type UpdatePrivacyDto = components["schemas"]["UpdatePrivacyDto"];
export type AvatarDto = components["schemas"]["AvatarDto"];
export type OtherProfileDto = components["schemas"]["OtherProfileDto"];
export type IsFollowingDto = components["schemas"]["IsFollowingDto"];
export type FollowRequestDto = components["schemas"]["FollowRequestDto"];
export type OkMessageDto = components["schemas"]["OkMessageDto"];
export type BlockedUserDto = components["schemas"]["BlockedUserDto"];
export type FollowerDto = components["schemas"]["FollowerDto"];
export type FollowResultDto = components["schemas"]["FollowResultDto"];
export type CloseFriendDto = components["schemas"]["CloseFriendDto"];
export type MusicDto = components["schemas"]["MusicDto"];
export type SaveMusicDto = components["schemas"]["SaveMusicDto"];
export type SpotifyTrackDto = components["schemas"]["SpotifyTrackDto"];
export type PostMediaDto = components["schemas"]["PostMediaDto"];
export type PostLocationDto = components["schemas"]["PostLocationDto"];
export type PostMusicDto = components["schemas"]["PostMusicDto"];
export type PostDto = components["schemas"]["PostDto"];
export type DeletedDto = components["schemas"]["DeletedDto"];
export type CommentLikeToggleDto = components["schemas"]["CommentLikeToggleDto"];
export type CreateCommentDto = components["schemas"]["CreateCommentDto"];
export type CommentDto = components["schemas"]["CommentDto"];
export type UpdatePostDto = components["schemas"]["UpdatePostDto"];
export type ArchiveDto = components["schemas"]["ArchiveDto"];
export type LikeToggleDto = components["schemas"]["LikeToggleDto"];
export type ViewDto = components["schemas"]["ViewDto"];
export type FavoriteToggleDto = components["schemas"]["FavoriteToggleDto"];
export type ShareDto = components["schemas"]["ShareDto"];
export type ShareResultDto = components["schemas"]["ShareResultDto"];
export type ReportPostDto = components["schemas"]["ReportPostDto"];
export type StoryMusicDto = components["schemas"]["StoryMusicDto"];
export type StoryDto = components["schemas"]["StoryDto"];
export type StoryRailItemDto = components["schemas"]["StoryRailItemDto"];
export type StoryLikeToggleDto = components["schemas"]["StoryLikeToggleDto"];
export type ReactionDto = components["schemas"]["ReactionDto"];
export type ReactionSentDto = components["schemas"]["ReactionSentDto"];
export type StoryReplyDto = components["schemas"]["StoryReplyDto"];
export type StoryViewerDto = components["schemas"]["StoryViewerDto"];
export type CreateHighlightDto = components["schemas"]["CreateHighlightDto"];
export type HighlightDto = components["schemas"]["HighlightDto"];
export type HighlightWithStoriesDto = components["schemas"]["HighlightWithStoriesDto"];
export type UpdateHighlightDto = components["schemas"]["UpdateHighlightDto"];
export type NoteMusicDto = components["schemas"]["NoteMusicDto"];
export type NoteDto = components["schemas"]["NoteDto"];
export type CreateNoteDto = components["schemas"]["CreateNoteDto"];
export type UpdateNoteDto = components["schemas"]["UpdateNoteDto"];
export type NoteLikeToggleDto = components["schemas"]["NoteLikeToggleDto"];
export type NoteLikeItemDto = components["schemas"]["NoteLikeItemDto"];
export type NoteReplyDto = components["schemas"]["NoteReplyDto"];
export type NoteReplySentDto = components["schemas"]["NoteReplySentDto"];
export type NoteReplyItemDto = components["schemas"]["NoteReplyItemDto"];
export type ChatListItemDto = components["schemas"]["ChatListItemDto"];
export type CreateChatDto = components["schemas"]["CreateChatDto"];
export type ChatCreatedDto = components["schemas"]["ChatCreatedDto"];
export type EditMessageDto = components["schemas"]["EditMessageDto"];
export type MessageReactionDto = components["schemas"]["MessageReactionDto"];
export type OkDto = components["schemas"]["OkDto"];
export type BulkDeleteDto = components["schemas"]["BulkDeleteDto"];
export type MessageRequestItemDto = components["schemas"]["MessageRequestItemDto"];
export type ChatDetailDto = components["schemas"]["ChatDetailDto"];
export type ThemeDto = components["schemas"]["ThemeDto"];
export type NicknameDto = components["schemas"]["NicknameDto"];
export type MuteDto = components["schemas"]["MuteDto"];
export type ReportChatDto = components["schemas"]["ReportChatDto"];
export type CallStartedDto = components["schemas"]["CallStartedDto"];
export type NotificationDto = components["schemas"]["NotificationDto"];
export type UnreadCountDto = components["schemas"]["UnreadCountDto"];
export type ProfileViewDto = components["schemas"]["ProfileViewDto"];
export type HashtagDto = components["schemas"]["HashtagDto"];
export type LocationBriefDto = components["schemas"]["LocationBriefDto"];
export type SearchResultDto = components["schemas"]["SearchResultDto"];
export type TopResultDto = components["schemas"]["TopResultDto"];
export type LocationDto = components["schemas"]["LocationDto"];
export type CreateLocationDto = components["schemas"]["CreateLocationDto"];
export type UpdateLocationDto = components["schemas"]["UpdateLocationDto"];
export type VerificationStatusDto = components["schemas"]["VerificationStatusDto"];
export type AdminUserDto = components["schemas"]["AdminUserDto"];
export type AdminOkDto = components["schemas"]["AdminOkDto"];
export type AdminReportDto = components["schemas"]["AdminReportDto"];
export type StartLiveDto = components["schemas"]["StartLiveDto"];
export type LiveDto = components["schemas"]["LiveDto"];
export type LiveTokenDto = components["schemas"]["LiveTokenDto"];
export type LiveOkDto = components["schemas"]["LiveOkDto"];
export type LiveStatsDto = components["schemas"]["LiveStatsDto"];
export type LiveViewerDto = components["schemas"]["LiveViewerDto"];
export type LiveCommentInputDto = components["schemas"]["LiveCommentInputDto"];
export type LiveCommentDto = components["schemas"]["LiveCommentDto"];
export type LiveLikeResultDto = components["schemas"]["LiveLikeResultDto"];
export type LiveReactionInputDto = components["schemas"]["LiveReactionInputDto"];
export type JoinRequestDto = components["schemas"]["JoinRequestDto"];
export type CameraDto = components["schemas"]["CameraDto"];
export type AudioDto = components["schemas"]["AudioDto"];
